### ISSUE TITLE
Add class when the modal is open

### ISSUE THREAD

**Issue by davidbwaters** [NigelGreenway/inuitcss.plugins.iglu#5]
Hi.  Please consider adding a class `.is-open` or similar (configurable, maybe?) when the modal is opened (right after it is created).  This would be a 'hook' to allow usage with CSS transitions for fading in opacity, etc., to be used.  

Thanks.

**Comment by NigelGreenway** [comment]
@davidbwaters That is a good suggestion. I can get round to this, but maybe a few weeks away. Happy for a PR though if this is something you are wanting quickly?
